#!/bin/bash
#
# chkconfig: 35 95 05
# description: Web based graphical interface for rsnapshot
# processname: hypnotoad
# pidfile: /var/run/webrsnapshot.pid

. /etc/rc.d/init.d/functions

RETVAL=0
prog="webrsnapshot"
PROGROOT=/opt/webrsnapshot
LOCKFILE=/var/lock/subsys/$prog

start() {
	if [ -f $LOCKFILE ] ; then
		echo "$prog is already running."
		return 1
	fi
	echo "Starting $prog: "
	daemon $PROGROOT/bin/hypnotoad $PROGROOT/webrsnapshot.pl
	RETVAL=$?
	[ $RETVAL -eq 0 ] && touch $LOCKFILE
	echo
	return $RETVAL
}

stop() {
	echo "Shutting down $prog: "
	$PROGROOT/bin/hypnotoad -s $PROGROOT/webrsnapshot.pl
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f $LOCKFILE
	return $RETVAL
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	reload | restart)
		stop
		start
		;;
	*)
		echo "Usage: $prog {start|stop|reload|restart}"
		exit 1
		;;
esac
exit $?
